Support Django 1.11
Warning: Django 1.8 seems not to uninstall cleanly, leading to
`ImportError: cannot import name RemovedInDjango19Warning`. This can be solved
by uninstalling Django, removing the Django shared library directory, and
re-installing, e.g.:

    root@kpi:/srv/src/kpi# pip uninstall Django
    root@kpi:/srv/src/kpi# rm -r /usr/local/lib/python2.7/dist-packages/django
    root@kpi:/srv/src/kpi# pip-sync dependencies/pip/external_services.txt

Trouble on the horizon: `pytest-django==3.4.7`, newer than what's included
here, causes many asset snapshot tests to fail. I have yet to investigate why.